### PR TITLE
Create views and controllers

### PR DESCRIPTION
**Pull request by NitBravoA92**
# 🚩IMPLEMENTATION DETAILS | create-views-and-controllers - >>branch<< -

### Hi there! @NitBravoA92 here. 👋

This is the PR for **Budget App - Ruby on Rails Capstone project**. The main goal of today's activity is to create all the logic to list categories, create a new category, list payments based on a selected category, and add new payments.

### Here is a summary of what has been done:

- [x] Create the functionality to display the list of categories in the `/categories` page

- [x] Create the functionality to add a new category in the `/categories/new` page

- [x] Create the functionality to list all the payments for a given category in the `/categories/:category_id/payments` page

- [x] Create the functionality to add a new payment in the `/payments/new` page

- [x] Create the navbar with the links to navigate through the app

- [x] Add the final styles of the application

- [x] Create the request and integration tests for all the controllers and views

- [x] Update the README.md file to document the project

## ⭐To the code reviewer 👨‍💻

💝 I really thank 🙇‍♂️ you, dear code reviewer 👨‍🎨 for dedicating your precious 🥇 time ⌚ to check the PR 🧾 .

I kindly ask 🙏 dear code reviewer 🤵 that if there is any issue 🦯 in this project, please do list 📃 them in a descriptive 💡 manner and give your best suggestions 🎁 if needed.

If you think some significant issues need to be changed ♻️ please kindly contact 📞 me through Zoom or Slack, I am available on Microverse UTC-6 time zone.

### CODE REVIEW

**Review by AndreaM2429 — APPROVED** [review]
# Status: Approved :green_circle:

### Hi @NitBravoA92  

Great work on implementing the new feature, this is complete so it's time to merge it 💯 🥳.

congrats

## Highlights :1st_place_medal:

- All tests are passing, an incredible job with that
- The models have correct validations and associations
- Good use of join_table
- The design match with the provided

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval._

As I mentioned before, all the designs match the ones provided for this project, but still there are some things you can do to improve it. Please remember this is completely optional and you don't need to make it.

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

----------------------------------------------------

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by AndreaM2429** [comment]
- You made a great job making the navbar fix but it would be better if you couldn't scroll down the page when it's only one card on it. ALso please check the forms on the add category, new transaction and the payments pages.

image
image

**Comment by AndreaM2429** [comment]
- Also you implemented the alerts for the form actions correctly but for a better user experience I suggested you to set a timer to quit them from the screen since it is bother.
I  mean this 👇🏽 
image

**Comment by NitBravoA92** [comment]
@AndreaM2429 All suggested changes were made. Thank you very much.

**Pull request merged**
